services:
  mysql:
    image: mysql:8.0
    container_name: quasar_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: quasar_gameshop_app
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    image: quasar-app
    container_name: quasar_app
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      MYSQL_HOST: mysql
    command: ["sh", "-c", "./wait-for-it.sh mysql:3306 -- java -jar app.jar"]

volumes:
  mysql_data:
