spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:3306/quasar_gameshop_app?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false

  sql:
    init:
      mode: always

  mvc:
    hiddenmethod:
      filter:
        enabled: true

quasar:
  remember.me.key: ${REMEMBER_ME_KEY}

mail:
  quasar: "info@quasargames.com"
  host: ${SMTP_HOST}
  port: ${SMTP_PORT}
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
